default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: admin1
  password: 123456
  host: localhost

development:
  <<: *default
  database: foods_drinks_development

test:
  <<: *default
  database: foods_drinks_test

production:
  <<: *default
  database: foods_drinks_production
