default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: foods_drinks_development
  username: admin1
  password: 123456
  host: localhost

test:
  <<: *default
  database: foods_drinks_test
  username: admin1
  password: 123456
  host: localhost

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
